---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    backstage.io/kubernetes-id: sock-shop-marghe
    app.kubernetes.io/name: sock-shop-marghe
    rht-gitops.com/janus-argocd: sock-shop-marghe
  name: storeuser-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    backstage.io/kubernetes-id: sock-shop-marghe
    app.kubernetes.io/name: sock-shop-marghe
    rht-gitops.com/janus-argocd: sock-shop-marghe
  name: storeuseradmin-sa
